# Generated by Django 3.0.5 on 2020-04-21 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input_cloud',
            fields=[
                ('input_id', models.IntegerField(primary_key=True, serialize=False)),
                ('input_cloud_2_url', models.CharField(max_length=255)),
                ('input_upload_time', models.DateTimeField(verbose_name='Upload time')),
            ],
        ),
        migrations.CreateModel(
            name='Input_Image',
            fields=[
                ('input_id', models.IntegerField(primary_key=True, serialize=False)),
                ('input_calib_url', models.CharField(max_length=255)),
                ('input_image_2_url', models.CharField(max_length=255)),
                ('input_label_2_url', models.CharField(max_length=255)),
                ('input_velodyne_url', models.CharField(max_length=255)),
                ('input_upload_time', models.DateTimeField(verbose_name='Upload time')),
            ],
        ),
        migrations.CreateModel(
            name='Output_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_folder_url', models.CharField(max_length=255)),
                ('input_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ioi.Input_Image')),
            ],
        ),
        migrations.CreateModel(
            name='Output_cloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_folder_url', models.CharField(max_length=255)),
                ('input_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ioi.Input_cloud')),
            ],
        ),
    ]
