# Generated by Django 3.0.3 on 2020-03-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ioi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input_image',
            old_name='input_image_upload_time',
            new_name='input_upload_time',
        ),
    ]
