# Generated by Django 3.0.3 on 2020-03-03 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ioi', '0002_auto_20200302_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='output_image',
            old_name='output_image_folder_url',
            new_name='output_folder_url',
        ),
    ]
